version: 2
jobs:
  build:
    docker:
      - image: docker:17.07.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t naari3/sample_with_redis:latest .
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker tag naari3/sample_with_redis:latest naari3/sample_with_redis:${CIRCLE_TAG}
      - run:
          command: docker push naari3/sample_with_redis:latest
      - run:
          command: docker push naari3/sample_with_redis:${CIRCLE_TAG}

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
